version: 3.2.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- ps: .\appveyor.ps1
build:
  project: src/Config.Net.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd src\Config.Net.Tests

    dotnet test

    cd ..\..
artifacts:
- path: src/**/*.nupkg
deploy:
- provider: Environment
  name: aloneguid NuGet