version: 4.2.0-preview-{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
- ps: .\appveyor.ps1
build:
  project: src/Config.Net.sln
  verbosity: minimal
test_script:
- cmd: >-
    cd src\Config.Net.Tests

    dotnet test

    cd ..\..
- whatever: test
artifacts:
- path: src/**/*.nupkg
deploy:
- provider: Environment
  name: aloneguid NuGet
  on:
    branch: /stable-\./